services:

  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/usr/share/nginx/html

  sass:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
    command: npx sass --watch Pages/scss:Pages