# Stage 1 — Build SCSS
FROM node:18 AS builder

WORKDIR /app

COPY . .

RUN npm install -g sass

RUN sass Pages/scss/style.scss Pages/style.css --style=compressed


# Stage 2 — Production server
FROM nginx:alpine

COPY --from=builder /app /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]